### ISSUE TITLE
Getting Started: Review project roadmap, tech docs

### ISSUE THREAD

**Issue by ShaneCurcuru** [ArlingtonMA/arlingtonma.info#1]
Greg - here's what would be useful for this week's volunteer time - seeing what I'm planning on building short-term, and checking in your edits/suggestions on where to go from there.

**Review & Comment**

- https://github.com/ArlingtonMA/arlingtonma.info/wiki/Project-Roadmap
- https://github.com/ArlingtonMA/arlingtonma.info/wiki/Tooling#likely-future-technical-direction
- https://github.com/ArlingtonMA/arlingtonma.info/wiki/How-To-Add-A-Dataset

- Add your name to the Home page in this wiki, and add a section (somewhere) with an About You - key skills you can use in this project, and what interest areas you'd like to work on.

**Comment by maxuser0** [comment]
Made minor edits to wiki pages, mainly grammar and spelling nits. Added myself to the wiki home page as a contributor.
